# Generated by Django 4.1 on 2022-08-18 06:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_downwote_count_post_upwote_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Following',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='follower',
            new_name='following',
        ),
    ]
