# Generated by Django 4.1 on 2022-08-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_readlater'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_user_following_combination'),
        ),
        migrations.AddConstraint(
            model_name='readlater',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_combination'),
        ),
    ]
